// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4xr3GPlYVf_ujzz3GcAZ_byYA_NrUpVo',
    appId: '1:516862105475:web:45a182f32a0052d09f88b6',
    messagingSenderId: '516862105475',
    projectId: 'blogcat-c398a',
    authDomain: 'blogcat-c398a.firebaseapp.com',
    storageBucket: 'blogcat-c398a.firebasestorage.app',
    measurementId: 'G-GBDPMPFXRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBp9XBwKXsxXvnjr4Vk8wFBIDOnKyqbak',
    appId: '1:516862105475:android:c158ec23c814dc8c9f88b6',
    messagingSenderId: '516862105475',
    projectId: 'blogcat-c398a',
    storageBucket: 'blogcat-c398a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjMJA9exVns6gcjtxB-Zmtr6dI6KaT2mU',
    appId: '1:516862105475:ios:3559ecb74c17313d9f88b6',
    messagingSenderId: '516862105475',
    projectId: 'blogcat-c398a',
    storageBucket: 'blogcat-c398a.firebasestorage.app',
    iosClientId: '516862105475-07sfp5btc44s42prn1bjpc41fdg5uk3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogcat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjMJA9exVns6gcjtxB-Zmtr6dI6KaT2mU',
    appId: '1:516862105475:ios:3559ecb74c17313d9f88b6',
    messagingSenderId: '516862105475',
    projectId: 'blogcat-c398a',
    storageBucket: 'blogcat-c398a.firebasestorage.app',
    iosClientId: '516862105475-07sfp5btc44s42prn1bjpc41fdg5uk3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogcat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4xr3GPlYVf_ujzz3GcAZ_byYA_NrUpVo',
    appId: '1:516862105475:web:05d155346a7f175c9f88b6',
    messagingSenderId: '516862105475',
    projectId: 'blogcat-c398a',
    authDomain: 'blogcat-c398a.firebaseapp.com',
    storageBucket: 'blogcat-c398a.firebasestorage.app',
    measurementId: 'G-4YB4SM7JY1',
  );
}
